name: Deploy Website

on:
  push:
    branches:
      - afnan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # STEP 1 — Download latest GitHub code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # STEP 2 — Upload website files to EC2 temp folder
      - name: Upload Website Files
        uses: appleboy/scp-action@v0.1.7

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          # Upload only website files
          source: "index.html,styles.css"

          # Temporary upload folder
          target: "/home/ubuntu/site-temp"

      # STEP 3 — Move files into nginx website folder
      - name: Deploy Files to Nginx
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            # Remove old website files
            sudo rm -rf /var/www/mysite/*

            # Copy new files
            sudo cp -r /home/ubuntu/site-temp/* /var/www/mysite/

            # Restart nginx
            sudo systemctl restart nginx

            # Show nginx status
            sudo systemctl status nginx
