name: Deploy Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Deploy Website
        run: |
          sudo mkdir -p /var/www/mysite

          sudo rsync -av --delete ./ /var/www/mysite/

          sudo systemctl restart nginx
