name: Deploy Static Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Website
        run: |
          sudo mkdir -p /var/www/html

          sudo rsync -av --delete ./ /var/www/html/
